# Generated by Django 2.1.2 on 2019-01-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_project_github_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tags',
            new_name='category',
        ),
        migrations.AddField(
            model_name='project',
            name='field',
            field=models.CharField(default='data science', max_length=50),
        ),
    ]
